### ISSUE TITLE
detect that bluetooth is disabled

### ISSUE THREAD

**Issue by autonome** [mozilla-magnet/magnet-client-desktop#4] opened 2016-07-25 18:45 UTC
I was wondering why my desktop broadcast wasn't being detected by the mobile client... and then realized that I'd disabled Bluetooth on the laptop.

The app should have some visual indicator in the toolbar icon (like a color change or something) and also a notice when you drop a URL and probably also something the menu itself.

**Comment by wilsonpage** [comment] 2016-08-02 19:55
Sorry, just saw this as I had notifications preffed on by mistake.

Yes I think perhaps changing the icon to something with cross through and then showing a message in the list like: 'Please turn on bluetooth'.

**Comment by wilsonpage** [comment] 2016-08-02 19:58
Duplicate of #3

**Closed as completed by wilsonpage** 2016-08-02 19:58 UTC
